services:
  db_kitchen_service:
    image: postgres
    container_name: db_kitchen_service
    environment:
      POSTGRES_DB: kitchen_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - kitchen_service_data:/var/lib/postgresql/data

volumes:
  kitchen_service_data: