create table waiter_order(
    id bigint primary key generated by default as identity,
    status varchar not null,
    create_dttm timestamp with time zone not null,
    waiter_id bigint not null references waiter_account(id),
    table_no varchar not null
);