create table order_position(
    id bigint primary key generated by default as identity,
    dish_num bigint not null,
    order_id bigint not null references waiter_order(id),
    menu_position_id bigint not null references menu(id)
);