server:
  port: 8080
  servlet:
    context-path: /kitchen-service
    session:
      timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/kitchen_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/main-changelog.xml
  cloud:
    openfeign:
      client:
        config:
          waiterFeignClient:
            url: http://localhost:8081/waiter-service
  kafka:
    bootstrap-servers:
      - localhost:29092
    producer:
      order-topic: waiterOrderToKitchenTopic
    consumer:
      group-id: kitchen-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: ru.liga.kitchen_service.models
  configuration:
    map-underscore-to-camel-case: true




