create table kitchen_order(
    id bigint primary key generated by default as identity,
    waiter_order_no bigint not null,
    status varchar not null,
    create_dttm timestamp with time zone not null
);