server:
  port: 8081
  servlet:
    context-path: /waiter-service
    session:
      timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
