server:
  port: 8081
  servlet:
    context-path: /waiter-service
    session:
      timeout: 10000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/waiter_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/main-changelog.xml
  cloud:
    openfeign:
      client:
        config:
          kitchenFeignClient:
            url: http://localhost:8080/kitchen-service

